version: "3.3"

services:
  web:
        build: .
        container_name: docker_ngx_small_light
        volumes:
        - ./src:/etc/nginx/html # "root" por defecto en Nginx
        - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
        - 8080:80

